In [1]:
#######################################################################################################################
# [PROBLEM STATEMENT]
# We have a dataset for the fire department of New York City.
# Analyze the dataset using pandas to determine:
#
# 1) The total number of fire department facilities in New York City
# 2) The number of fire department facilities in each borough
# 3) The names of facilities in Manhattan
#######################################################################################################################
# AUTHOR  : Aditya Saxena
# DATE    : August 28, 2022
# VERSION : 1.0
#######################################################################################################################

In [4]:
# [IMPORTING THE REQUIRED LIBRARIES]
import pandas as pd
import numpy  as nu

In [9]:
# [READ THE DATA FROM THE CSV FILE FOR FIRE DEPARTMENT OF NEW YORK]
df_fdny_csv_data_raw = pd.read_csv('//Users//adityasaxena//Desktop//MyProjects//Data_Science_with_Python//Introduction to Pandas//fdny-firehouse-listing.csv')

In [10]:
# [DISPLAYING THE DATA]
df_fdny_csv_data_raw

,FacilityName,FacilityAddress,Borough,Postcode,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,Engine 4/Ladder 15,42 South Street,Manhattan,10005.0,40.703466,-74.007538,1.0,1.0,7.0,1000867.0,1.000350e+09,Battery Park City-Lower Manhattan ...
1,Engine 10/Ladder 10,124 Liberty Street,Manhattan,10006.0,40.710072,-74.012523,1.0,1.0,13.0,1075700.0,1.000520e+09,Battery Park City-Lower Manhattan ...
2,Engine 6,49 Beekman Street,Manhattan,10038.0,40.710048,-74.005245,1.0,1.0,1501.0,1001287.0,1.000930e+09,Battery Park City-Lower Manhattan ...
3,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan,10007.0,40.715463,-74.005938,1.0,1.0,33.0,1001647.0,1.001500e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
4,Ladder 8,14 North Moore Street,Manhattan,10013.0,40.719759,-74.006678,1.0,1.0,33.0,1002150.0,1.001890e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
...,...,...,...,...,...,...,...,...,...,...,...,...
213,Engine 162/Ladder 82/Battalion 23,256 Nelson Avenue,Staten Island,10308.0,40.543205,-74.147097,3.0,51.0,15601.0,5067428.0,5.052710e+09,Great Kills ...
214,Engine 167/Ladder 87,345 Annadale Road,Staten Island,10312.0,40.554174,-74.175809,3.0,51.0,17012.0,5075428.0,5.056420e+09,Annadale-Huguenot-Prince's Bay-Eltingville ...
215,Engine 164/Ladder 84,1560 Drumgoole Road West,Staten Island,10312.0,40.535332,-74.195611,3.0,51.0,20804.0,5083491.0,5.068280e+09,Rossville-Woodrow ...
216,Engine 168/EMS Station 23,1100 Rossville Avenue,Staten Island,10309.0,40.553977,-74.212812,3.0,51.0,20801.0,5154879.0,5.070670e+09,Rossville-Woodrow ...
217,Engine 151/Ladder 76,7219 Amboy Road,Staten Island,10307.0,40.512518,-74.238822,3.0,51.0,248.0,5089056.0,5.080400e+09,Charleston-Richmond Valley-Tottenville ...

In [19]:
# [VIEW CONTENT OF THE DATA]
df_fdny_csv_data_raw.describe()

,Postcode,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL
count,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,2.130000e+02,2.130000e+02
mean,10783.774648,40.719125,-73.937440,7.075117,25.629108,5949.535211,2.900421e+06,2.849843e+09
std,556.522394,0.083674,0.093686,7.033880,15.648512,19571.786111,1.306104e+06,1.285511e+09
min,10001.000000,40.512518,-74.238822,1.000000,1.000000,1.000000,1.000867e+06,1.000350e+09
25%,10304.000000,40.663404,-73.987182,3.000000,12.000000,129.000000,2.003268e+06,2.025140e+09
50%,11103.000000,40.715147,-73.938066,6.000000,27.000000,275.000000,3.064786e+06,3.024650e+09
75%,11231.000000,40.774505,-73.886796,11.000000,38.000000,800.000000,4.090228e+06,4.032940e+09
max,11695.000000,40.892803,-73.716559,84.000000,51.000000,157902.000000,5.154879e+06,5.080400e+09

In [21]:
# [VIEW CONTENT OF THE DATA] - Dirty Method - Do not use
df_fdny_csv_data.describe

<bound method NDFrame.describe of                                     Engine 4/Ladder 15  \
0                                  Engine 10/Ladder 10
1                                             Engine 6
2    Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...
3                                             Ladder 8
4                                    Engine 9/Ladder 6
..                                                 ...
212                  Engine 162/Ladder 82/Battalion 23
213                               Engine 167/Ladder 87
214                               Engine 164/Ladder 84
215                          Engine 168/EMS Station 23
216                               Engine 151/Ladder 76

              42 South Street      Manhattan    10005  40.703466  -74.007538  \
0          124 Liberty Street      Manhattan  10006.0  40.710072  -74.012523
1           49 Beekman Street      Manhattan  10038.0  40.710048  -74.005245
2        100-104 Duane Street      Manhattan  10007.0  40.715463  -74.005938
3       14 North Moore Street      Manhattan  10013.0  40.719759  -74.006678
4             75 Canal Street      Manhattan  10002.0  40.715213  -73.992901
..                        ...            ...      ...        ...         ...
212         256 Nelson Avenue  Staten Island  10308.0  40.543205  -74.147097
213         345 Annadale Road  Staten Island  10312.0  40.554174  -74.175809
214  1560 Drumgoole Road West  Staten Island  10312.0  40.535332  -74.195611
215     1100 Rossville Avenue  Staten Island  10309.0  40.553977  -74.212812
216           7219 Amboy Road  Staten Island  10307.0  40.512518  -74.238822

       1   1.1        7    1000867    1000350001  \
0    1.0   1.0     13.0  1075700.0  1.000520e+09
1    1.0   1.0   1501.0  1001287.0  1.000930e+09
2    1.0   1.0     33.0  1001647.0  1.001500e+09
3    1.0   1.0     33.0  1002150.0  1.001890e+09
4    3.0   1.0     16.0  1003898.0  1.003000e+09
..   ...   ...      ...        ...           ...
212  3.0  51.0  15601.0  5067428.0  5.052710e+09
213  3.0  51.0  17012.0  5075428.0  5.056420e+09
214  3.0  51.0  20804.0  5083491.0  5.068280e+09
215  3.0  51.0  20801.0  5154879.0  5.070670e+09
216  3.0  51.0    248.0  5089056.0  5.080400e+09

    Battery Park City-Lower Manhattan
0    Battery Park City-Lower Manhattan             ...
1    Battery Park City-Lower Manhattan             ...
2    SoHo-TriBeCa-Civic Center-Little Italy        ...
3    SoHo-TriBeCa-Civic Center-Little Italy        ...
4    Chinatown                                     ...
..                                                 ...
212  Great Kills                                   ...
213  Annadale-Huguenot-Prince's Bay-Eltingville    ...
214  Rossville-Woodrow                             ...
215  Rossville-Woodrow                             ...
216  Charleston-Richmond Valley-Tottenville        ...

[217 rows x 12 columns]>

In [15]:
# [VIEW FIRST SIX RECORDS]
df_fdny_csv_data_raw.head(6)

,FacilityName,FacilityAddress,Borough,Postcode,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,Engine 4/Ladder 15,42 South Street,Manhattan,10005.0,40.703466,-74.007538,1.0,1.0,7.0,1000867.0,1.000350e+09,Battery Park City-Lower Manhattan ...
1,Engine 10/Ladder 10,124 Liberty Street,Manhattan,10006.0,40.710072,-74.012523,1.0,1.0,13.0,1075700.0,1.000520e+09,Battery Park City-Lower Manhattan ...
2,Engine 6,49 Beekman Street,Manhattan,10038.0,40.710048,-74.005245,1.0,1.0,1501.0,1001287.0,1.000930e+09,Battery Park City-Lower Manhattan ...
3,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan,10007.0,40.715463,-74.005938,1.0,1.0,33.0,1001647.0,1.001500e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
4,Ladder 8,14 North Moore Street,Manhattan,10013.0,40.719759,-74.006678,1.0,1.0,33.0,1002150.0,1.001890e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
5,Engine 9/Ladder 6,75 Canal Street,Manhattan,10002.0,40.715213,-73.992901,3.0,1.0,16.0,1003898.0,1.003000e+09,Chinatown ...

In [16]:
# [SKIP THE FIRST ROW FROM DATASET]
df_fdny_csv_data = pd.read_csv('//Users//adityasaxena//Desktop//MyProjects//Data_Science_with_Python//Introduction to Pandas//fdny-firehouse-listing.csv', skiprows=1)

In [22]:
# [VIEW FIRST FIVE RECORDS FROM FIXED DATASET]
df_fdny_csv_data.head(5)

,Engine 4/Ladder 15,42 South Street,Manhattan,10005,40.703466,-74.007538,1,1.1,7,1000867,1000350001,Battery Park City-Lower Manhattan
0,Engine 10/Ladder 10,124 Liberty Street,Manhattan,10006.0,40.710072,-74.012523,1.0,1.0,13.0,1075700.0,1.000520e+09,Battery Park City-Lower Manhattan ...
1,Engine 6,49 Beekman Street,Manhattan,10038.0,40.710048,-74.005245,1.0,1.0,1501.0,1001287.0,1.000930e+09,Battery Park City-Lower Manhattan ...
2,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan,10007.0,40.715463,-74.005938,1.0,1.0,33.0,1001647.0,1.001500e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
3,Ladder 8,14 North Moore Street,Manhattan,10013.0,40.719759,-74.006678,1.0,1.0,33.0,1002150.0,1.001890e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
4,Engine 9/Ladder 6,75 Canal Street,Manhattan,10002.0,40.715213,-73.992901,3.0,1.0,16.0,1003898.0,1.003000e+09,Chinatown ...

In [20]:
# [VIEW DATA STATISTICS USING describe()]
df_fdny_csv_data.describe()

,10005,40.703466,-74.007538,1,1.1,7,1000867,1000350001
count,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,2.120000e+02,2.120000e+02
mean,10787.448113,40.719199,-73.937110,7.103774,25.745283,5977.566038,2.909382e+06,2.858567e+09
std,555.245091,0.083865,0.093783,7.038054,15.593206,19613.823802,1.302617e+06,1.282217e+09
min,10001.000000,40.512518,-74.238822,1.000000,1.000000,1.000000,1.001287e+06,1.000520e+09
25%,10304.750000,40.662772,-73.985260,3.000000,12.750000,129.750000,2.004379e+06,2.026258e+09
50%,11104.000000,40.715180,-73.937451,6.000000,27.000000,276.000000,3.066342e+06,3.025125e+09
75%,11231.000000,40.775525,-73.886782,11.000000,38.000000,806.000000,4.090558e+06,4.033955e+09
max,11695.000000,40.892803,-73.716559,84.000000,51.000000,157902.000000,5.154879e+06,5.080400e+09

In [23]:
# [VIEW COLUMNS OF DATASET]
df_fdny_csv_data.columns

Index(['Engine 4/Ladder 15', '42 South Street', 'Manhattan', '10005',
       '40.703466', '-74.007538', '1', '1.1', '7', '1000867', '1000350001',
       'Battery Park City-Lower Manhattan                                          '],
      dtype='object')

In [24]:
# [VIEW INDEX OF DATASET]
df_fdny_csv_data.index

RangeIndex(start=0, stop=217, step=1)

In [26]:
# [COUNT NUMBER OF RECORDS]
df_fdny_csv_data.count()

Engine 4/Ladder 15                                                             217
42 South Street                                                                217
Manhattan                                                                      217
10005                                                                          212
40.703466                                                                      212
-74.007538                                                                     212
1                                                                              212
1.1                                                                            212
7                                                                              212
1000867                                                                        212
1000350001                                                                     212
Battery Park City-Lower Manhattan                                              212
dtype: int64

In [27]:
# [COUNT NUMBER OF RECORDS] - DIRTY METHOD - do not use
df_fdny_csv_data.count

<bound method DataFrame.count of                                     Engine 4/Ladder 15  \
0                                  Engine 10/Ladder 10
1                                             Engine 6
2    Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...
3                                             Ladder 8
4                                    Engine 9/Ladder 6
..                                                 ...
212                  Engine 162/Ladder 82/Battalion 23
213                               Engine 167/Ladder 87
214                               Engine 164/Ladder 84
215                          Engine 168/EMS Station 23
216                               Engine 151/Ladder 76

              42 South Street      Manhattan    10005  40.703466  -74.007538  \
0          124 Liberty Street      Manhattan  10006.0  40.710072  -74.012523
1           49 Beekman Street      Manhattan  10038.0  40.710048  -74.005245
2        100-104 Duane Street      Manhattan  10007.0  40.715463  -74.005938
3       14 North Moore Street      Manhattan  10013.0  40.719759  -74.006678
4             75 Canal Street      Manhattan  10002.0  40.715213  -73.992901
..                        ...            ...      ...        ...         ...
212         256 Nelson Avenue  Staten Island  10308.0  40.543205  -74.147097
213         345 Annadale Road  Staten Island  10312.0  40.554174  -74.175809
214  1560 Drumgoole Road West  Staten Island  10312.0  40.535332  -74.195611
215     1100 Rossville Avenue  Staten Island  10309.0  40.553977  -74.212812
216           7219 Amboy Road  Staten Island  10307.0  40.512518  -74.238822

       1   1.1        7    1000867    1000350001  \
0    1.0   1.0     13.0  1075700.0  1.000520e+09
1    1.0   1.0   1501.0  1001287.0  1.000930e+09
2    1.0   1.0     33.0  1001647.0  1.001500e+09
3    1.0   1.0     33.0  1002150.0  1.001890e+09
4    3.0   1.0     16.0  1003898.0  1.003000e+09
..   ...   ...      ...        ...           ...
212  3.0  51.0  15601.0  5067428.0  5.052710e+09
213  3.0  51.0  17012.0  5075428.0  5.056420e+09
214  3.0  51.0  20804.0  5083491.0  5.068280e+09
215  3.0  51.0  20801.0  5154879.0  5.070670e+09
216  3.0  51.0    248.0  5089056.0  5.080400e+09

    Battery Park City-Lower Manhattan
0    Battery Park City-Lower Manhattan             ...
1    Battery Park City-Lower Manhattan             ...
2    SoHo-TriBeCa-Civic Center-Little Italy        ...
3    SoHo-TriBeCa-Civic Center-Little Italy        ...
4    Chinatown                                     ...
..                                                 ...
212  Great Kills                                   ...
213  Annadale-Huguenot-Prince's Bay-Eltingville    ...
214  Rossville-Woodrow                             ...
215  Rossville-Woodrow                             ...
216  Charleston-Richmond Valley-Tottenville        ...

[217 rows x 12 columns]>

In [28]:
# [VIEW DATATYPES]
df_fdny_csv_data.dtypes

Engine 4/Ladder 15                                                              object
42 South Street                                                                 object
Manhattan                                                                       object
10005                                                                          float64
40.703466                                                                      float64
-74.007538                                                                     float64
1                                                                              float64
1.1                                                                            float64
7                                                                              float64
1000867                                                                        float64
1000350001                                                                     float64
Battery Park City-Lower Manhattan                                               object
dtype: object

In [34]:
# [DISPLAY FDNY INFORMATION]
df_fdny_csv_data

,Engine 4/Ladder 15,42 South Street,Manhattan,10005,40.703466,-74.007538,1,1.1,7,1000867,1000350001,Battery Park City-Lower Manhattan
0,Engine 10/Ladder 10,124 Liberty Street,Manhattan,10006.0,40.710072,-74.012523,1.0,1.0,13.0,1075700.0,1.000520e+09,Battery Park City-Lower Manhattan ...
1,Engine 6,49 Beekman Street,Manhattan,10038.0,40.710048,-74.005245,1.0,1.0,1501.0,1001287.0,1.000930e+09,Battery Park City-Lower Manhattan ...
2,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan,10007.0,40.715463,-74.005938,1.0,1.0,33.0,1001647.0,1.001500e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
3,Ladder 8,14 North Moore Street,Manhattan,10013.0,40.719759,-74.006678,1.0,1.0,33.0,1002150.0,1.001890e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
4,Engine 9/Ladder 6,75 Canal Street,Manhattan,10002.0,40.715213,-73.992901,3.0,1.0,16.0,1003898.0,1.003000e+09,Chinatown ...
...,...,...,...,...,...,...,...,...,...,...,...,...
212,Engine 162/Ladder 82/Battalion 23,256 Nelson Avenue,Staten Island,10308.0,40.543205,-74.147097,3.0,51.0,15601.0,5067428.0,5.052710e+09,Great Kills ...
213,Engine 167/Ladder 87,345 Annadale Road,Staten Island,10312.0,40.554174,-74.175809,3.0,51.0,17012.0,5075428.0,5.056420e+09,Annadale-Huguenot-Prince's Bay-Eltingville ...
214,Engine 164/Ladder 84,1560 Drumgoole Road West,Staten Island,10312.0,40.535332,-74.195611,3.0,51.0,20804.0,5083491.0,5.068280e+09,Rossville-Woodrow ...
215,Engine 168/EMS Station 23,1100 Rossville Avenue,Staten Island,10309.0,40.553977,-74.212812,3.0,51.0,20801.0,5154879.0,5.070670e+09,Rossville-Woodrow ...
216,Engine 151/Ladder 76,7219 Amboy Road,Staten Island,10307.0,40.512518,-74.238822,3.0,51.0,248.0,5089056.0,5.080400e+09,Charleston-Richmond Valley-Tottenville ...

In [36]:
# [THE ABOVE DATAS DOES NOT HAVE THE TERM BOROUGH. HENCE WE WILL HAVE TO GO TO THE RAW DATA]
df_fdny_csv_data_new = pd.read_csv('//Users//adityasaxena//Desktop//MyProjects//Data_Science_with_Python//Introduction to Pandas//fdny-firehouse-listing.csv')

In [37]:
df_fdny_csv_data_new

,FacilityName,FacilityAddress,Borough,Postcode,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,Engine 4/Ladder 15,42 South Street,Manhattan,10005.0,40.703466,-74.007538,1.0,1.0,7.0,1000867.0,1.000350e+09,Battery Park City-Lower Manhattan ...
1,Engine 10/Ladder 10,124 Liberty Street,Manhattan,10006.0,40.710072,-74.012523,1.0,1.0,13.0,1075700.0,1.000520e+09,Battery Park City-Lower Manhattan ...
2,Engine 6,49 Beekman Street,Manhattan,10038.0,40.710048,-74.005245,1.0,1.0,1501.0,1001287.0,1.000930e+09,Battery Park City-Lower Manhattan ...
3,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan,10007.0,40.715463,-74.005938,1.0,1.0,33.0,1001647.0,1.001500e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
4,Ladder 8,14 North Moore Street,Manhattan,10013.0,40.719759,-74.006678,1.0,1.0,33.0,1002150.0,1.001890e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
...,...,...,...,...,...,...,...,...,...,...,...,...
213,Engine 162/Ladder 82/Battalion 23,256 Nelson Avenue,Staten Island,10308.0,40.543205,-74.147097,3.0,51.0,15601.0,5067428.0,5.052710e+09,Great Kills ...
214,Engine 167/Ladder 87,345 Annadale Road,Staten Island,10312.0,40.554174,-74.175809,3.0,51.0,17012.0,5075428.0,5.056420e+09,Annadale-Huguenot-Prince's Bay-Eltingville ...
215,Engine 164/Ladder 84,1560 Drumgoole Road West,Staten Island,10312.0,40.535332,-74.195611,3.0,51.0,20804.0,5083491.0,5.068280e+09,Rossville-Woodrow ...
216,Engine 168/EMS Station 23,1100 Rossville Avenue,Staten Island,10309.0,40.553977,-74.212812,3.0,51.0,20801.0,5154879.0,5.070670e+09,Rossville-Woodrow ...
217,Engine 151/Ladder 76,7219 Amboy Road,Staten Island,10307.0,40.512518,-74.238822,3.0,51.0,248.0,5089056.0,5.080400e+09,Charleston-Richmond Valley-Tottenville ...

In [44]:
# [VIEW FDNY INFORMATION BOROUGHWISE]
groupby_boroughwise = df_fdny_csv_data_new.groupby('Borough')

In [45]:
# [VIEW FDNY INFORMATION FOR EACH BOROUGH]
groupby_boroughwise.size()

Borough
Bronx            34
Brooklyn         66
Manhattan        48
Queens           50
Staten Island    20
dtype: int64

In [46]:
# [SELECT FDNY INFORMATION FOR MANHATTAN]
fdny_info_Manhattan = groupby_boroughwise.get_group('Manhattan')

In [47]:
# [VIEW FDNY INFORMATION FOR MANHATTAN]
fdny_info_Manhattan

,FacilityName,FacilityAddress,Borough,Postcode,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,Engine 4/Ladder 15,42 South Street,Manhattan,10005.0,40.703466,-74.007538,1.0,1.0,7.0,1000867.0,1.000350e+09,Battery Park City-Lower Manhattan ...
1,Engine 10/Ladder 10,124 Liberty Street,Manhattan,10006.0,40.710072,-74.012523,1.0,1.0,13.0,1075700.0,1.000520e+09,Battery Park City-Lower Manhattan ...
2,Engine 6,49 Beekman Street,Manhattan,10038.0,40.710048,-74.005245,1.0,1.0,1501.0,1001287.0,1.000930e+09,Battery Park City-Lower Manhattan ...
3,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan,10007.0,40.715463,-74.005938,1.0,1.0,33.0,1001647.0,1.001500e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
4,Ladder 8,14 North Moore Street,Manhattan,10013.0,40.719759,-74.006678,1.0,1.0,33.0,1002150.0,1.001890e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
5,Engine 9/Ladder 6,75 Canal Street,Manhattan,10002.0,40.715213,-73.992901,3.0,1.0,16.0,1003898.0,1.003000e+09,Chinatown ...
6,Engine 15/Ladder 18/Battalion 4,25 Pitt Street,Manhattan,10002.0,40.716395,-73.983478,3.0,1.0,12.0,1004078.0,1.003420e+09,Lower East Side ...
7,Engine 28/Ladder 11,222 East 2nd Street,Manhattan,10009.0,40.721682,-73.982622,3.0,2.0,2202.0,1004608.0,1.003850e+09,Lower East Side ...
8,Engine 5,340 East 14th Street,Manhattan,10003.0,40.731752,-73.983536,3.0,2.0,40.0,1006520.0,1.004550e+09,East Village ...
9,Engine 55,363 Broome Street,Manhattan,10013.0,40.720033,-73.995689,2.0,1.0,41.0,1066722.0,1.004700e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
10,Ladder 20/Division 1,253 Lafayette Street,Manhattan,10012.0,40.723072,-73.996804,2.0,1.0,43.0,1007523.0,1.004950e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
11,Engine 24/Ladder 5/Battalion 2,227-29 6th Avenue,Manhattan,10014.0,40.727914,-74.003157,2.0,3.0,37.0,1080044.0,1.005200e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
12,Engine 33/Ladder 9,42 Great Jones Street,Manhattan,10012.0,40.726815,-73.992643,2.0,1.0,5502.0,1008526.0,1.005310e+09,West Village ...
13,Ladder 3/Battalion 6,108 East 13th Street,Manhattan,10003.0,40.733329,-73.989421,3.0,2.0,42.0,1009010.0,1.005580e+09,East Village ...
14,Squad 18,132 West 10th Street,Manhattan,10014.0,40.734625,-74.000346,2.0,3.0,71.0,1010686.0,1.006100e+09,West Village ...
15,Engine 34/Ladder 21,440 West 38th Street,Manhattan,10018.0,40.756635,-73.996217,4.0,3.0,111.0,1012982.0,1.007350e+09,Hudson Yards-Chelsea-Flatiron-Union Square ...
16,Engine 26,220 West 37th Street,Manhattan,10018.0,40.753239,-73.990078,5.0,3.0,109.0,1014447.0,1.007860e+09,Midtown-Midtown South ...
17,Engine 3/Ladder 12/Battalion 7,150 West 19th Street,Manhattan,10011.0,40.741044,-73.996041,4.0,3.0,87.0,1014724.0,1.007940e+09,Hudson Yards-Chelsea-Flatiron-Union Square ...
18,Engine 1/Ladder 24,142-46 West 31st Street,Manhattan,10001.0,40.748430,-73.990447,5.0,3.0,101.0,1015173.0,1.008060e+09,Midtown-Midtown South ...
19,Engine 14,14 East 18th Street,Manhattan,10003.0,40.738143,-73.990964,5.0,2.0,52.0,1016141.0,1.008460e+09,Hudson Yards-Chelsea-Flatiron-Union Square ...
20,Engine 16 / Ladder 7,234 East 29th Street,Manhattan,10016.0,40.742209,-73.979535,6.0,2.0,66.0,1019903.0,1.009090e+09,Murray Hill-Kips Bay ...
21,Engine 21,238 East 40th Street,Manhattan,10016.0,40.748845,-73.973888,6.0,4.0,88.0,1020385.0,1.009200e+09,Turtle Bay-East Midtown ...
22,Engine 54/Ladder 4/Battalion 9,782 8th Avenue,Manhattan,10036.0,40.760792,-73.987182,5.0,3.0,125.0,1024767.0,1.010190e+09,Midtown-Midtown South ...
23,Engine 23,215 West 58th Street,Manhattan,10019.0,40.766544,-73.980350,5.0,4.0,137.0,1024915.0,1.010300e+09,Midtown-Midtown South ...
24,Rescue 1,530 West 43rd Street,Manhattan,10036.0,40.760892,-73.996405,4.0,3.0,129.0,1070109.0,1.010710e+09,Clinton ...
25,Engine 40/Ladder 35,131 Amsterdam Avenue,Manhattan,10023.0,40.774505,-73.984619,7.0,6.0,149.0,1077844.0,1.011378e+09,Lincoln Square ...
26,Ladder 25/District Office 4/Division 3,205-207 West 77th Street,Manhattan,10024.0,40.781992,-73.979627,7.0,6.0,163.0,1030885.0,1.011690e+09,Upper West Side ...
27,Engine 74,120 West 83rd Street,Manhattan,10024.0,40.784881,-73.974434,7.0,6.0,169.0,1032079.0,1.012130e+09,Upper West Side ...
28,Engine 65,33 West 43rd Street,Manhattan,10036.0,40.754676,-73.981610,5.0,4.0,96.0,1076256.0,1.012590e+09,Midtown-Midtown South ...
29,Engine 8 / Ladder 2 / Battalion 8,167 East 51st Street,Manhattan,10022.0,40.756812,-73.971142,6.0,4.0,100.0,1036462.0,1.013060e+09,Turtle Bay-East Midtown ...
30,Engine 39/Ladder 16,157-59 East 67th Street,Manhattan,10065.0,40.766960,-73.963856,8.0,4.0,120.0,1072190.0,1.014020e+09,Upper East Side-Carnegie Hill ...
31,Engine 44,221 East 75th Street,Manhattan,10021.0,40.771427,-73.958521,8.0,4.0,134.0,1044059.0,1.014300e+09,Lenox Hill-Roosevelt Island ...
32,Engine 22/Ladder 13/Battalion 10,159 East 85th Street,Manhattan,10028.0,40.778584,-73.955516,8.0,5.0,14801.0,1047937.0,1.015140e+09,Upper East Side-Carnegie Hill ...
33,Engine 58/Ladder 26,1367 5th Avenue,Manhattan,10029.0,40.798873,-73.947759,11.0,9.0,184.0,1080501.0,1.016180e+09,East Harlem North ...
34,Engine 53/Ladder 43,1836-46 3rd Avenue,Manhattan,10029.0,40.788714,-73.946774,11.0,8.0,166.0,1051850.0,1.016290e+09,East Harlem South ...
35,Engine 91,242 East 111th Street,Manhattan,10029.0,40.794327,-73.941345,11.0,8.0,180.0,1052473.0,1.016600e+09,East Harlem North ...
36,Engine 35/Ladder 14,2282 3rd Avenue,Manhattan,10035.0,40.803129,-73.936244,11.0,8.0,196.0,1054465.0,1.017730e+09,East Harlem North ...
37,Engine 76/Ladder 22/Battalion 11,145-51 West 100th Street,Manhattan,10025.0,40.795924,-73.966726,7.0,7.0,189.0,1055910.0,1.018550e+09,Upper West Side ...
38,Engine 47,502 West 113th Street,Manhattan,10025.0,40.805068,-73.962929,9.0,7.0,199.0,1057000.0,1.018840e+09,Morningside Heights ...
39,Engine 59/Ladder 30,111 West 133rd Street,Manhattan,10030.0,40.813057,-73.942358,10.0,9.0,226.0,1058225.0,1.019180e+09,Central Harlem North-Polo Grounds ...
40,Engine 37/Ladder 40,415 West 125th Street,Manhattan,10027.0,40.811770,-73.954858,9.0,7.0,20901.0,1059547.0,1.019660e+09,Morningside Heights ...
41,Engine 69/Ladder 28/Battalion 16,248 West 143rd Street,Manhattan,10030.0,40.821105,-73.941849,10.0,9.0,232.0,1075491.0,1.020280e+09,Central Harlem North-Polo Grounds ...
42,Engine 80/Ladder 23,503 West 139th Street,Manhattan,10031.0,40.821586,-73.950689,9.0,7.0,225.0,1075504.0,1.020710e+09,Hamilton Heights ...
43,Engine 84/Ladder 34,513 West 161st Street,Manhattan,10032.0,40.835640,-73.940856,12.0,7.0,245.0,1062872.0,1.021200e+09,Washington Heights South ...
44,Engine 67,518 West 170th Street,Manhattan,10032.0,40.841394,-73.936836,12.0,10.0,253.0,1063024.0,1.021260e+09,Washington Heights South ...
45,Engine 93/Ladder 45/Battalion 13,515 West 181st Street,Manhattan,10033.0,40.848398,-73.931516,12.0,10.0,269.0,1075518.0,1.021550e+09,Washington Heights North ...
46,Engine 95/Ladder 36,29 Vermilyea Avenue,Manhattan,10034.0,40.864975,-73.925403,12.0,10.0,291.0,1064801.0,1.022240e+09,Marble Hill-Inwood ...
47,Marine 1,Little West 12th Street/Hudson River,Manhattan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN